In [2]:
import pandas as pd
import numpy as np

X_train = pd.read_csv('./datasets/TON-IoT/ton_iot_train.csv')
X_test = pd.read_csv('./datasets/TON-IoT/ton_iot_test.csv')
X = pd.concat([X_train, X_test])
X.sort_values(by='ID', ascending=True, inplace=True)

In [3]:
X

ID                src_ip               dst_ip     proto   service  \
274326       0   172.27.226.140:1883  192.168.1.152:52976  0.798147  0.260632   
179598       1   172.24.99.246:47260  192.168.1.255:15600 -1.252024  0.260632   
67026        2    172.18.57.119:1880  192.168.1.152:51782  0.798147  0.260632   
101166       3   172.18.164.17:34296  192.168.1.152:10502  0.798147  0.260632   
4404         4    172.29.91.92:46608     192.168.1.190:53 -1.252024 -1.502312   
...        ...                   ...                  ...       ...       ...   
123902  461038   172.20.31.166:33108     176.28.50.165:80  0.798147  0.260632   
70894   461039  172.20.166.189:37242    34.230.157.88:443  0.798147  0.260632   
225765  461040   172.29.243.207:4444  192.168.1.193:49178  0.798147  0.260632   
305332  461041   172.30.171.98:60816    104.98.29.100:443  0.798147  0.260632   
154449  461042   172.24.250.26:41054    151.101.24.64:443  0.798147  0.260632   

          duration  src_bytes  dst_bytes  conn_state  missed_bytes  ...  \
274326  160.494251   0.125981   3.392807   -0.679894     -0.004621  ...   
179598   -0.017933  -0.011044  -0.010582   -0.341502     -0.004621  ...   
67026    -0.017933  -0.011044  -0.010582   -0.679894     -0.004621  ...   
101166   -0.017933  -0.011044  -0.010582   -0.679894     -0.004621  ...   
4404     -0.017932  -0.011044  -0.010558   -1.231669     -0.004621  ...   
...            ...        ...        ...         ...           ...  ...   
123902   -0.017933  -0.011044  -0.010582   -0.341502     -0.004621  ...   
70894    -0.017933  -0.011044  -0.010582   -0.679894     -0.004621  ...   
225765    0.560694  -0.003149  -0.010371   -0.679894     -0.004621  ...   
305332    0.028280  -0.011042  -0.010579   -0.028912     -0.004621  ...   
154449    0.027645  -0.011042  -0.010579   -0.028912     -0.004621  ...   

        http_trans_depth  http_method  http_version  http_request_body_len  \
274326          0.022966     0.021033      0.022685               -0.00539   
179598          0.022966     0.021033      0.022685               -0.00539   
67026           0.022966     0.021033      0.022685               -0.00539   
101166          0.022966     0.021033      0.022685               -0.00539   
4404            0.022966     0.021033      0.022685               -0.00539   
...                  ...          ...           ...                    ...   
123902          0.022966     0.021033      0.022685               -0.00539   
70894           0.022966     0.021033      0.022685               -0.00539   
225765          0.022966     0.021033      0.022685               -0.00539   
305332          0.022966     0.021033      0.022685               -0.00539   
154449          0.022966     0.021033      0.022685               -0.00539   

        http_response_body_len  http_status_code  http_orig_mime_types  \
274326               -0.003103          0.018893              0.006307   
179598               -0.003103          0.018893              0.006307   
67026                -0.003103          0.018893              0.006307   
101166               -0.003103          0.018893              0.006307   
4404                 -0.003103          0.018893              0.006307   
...                        ...               ...                   ...   
123902               -0.003103          0.018893              0.006307   
70894                -0.003103          0.018893              0.006307   
225765               -0.003103          0.018893              0.006307   
305332               -0.003103          0.018893              0.006307   
154449               -0.003103          0.018893              0.006307   

        http_resp_mime_types  label  type  
274326               0.00171      0     0  
179598               0.00171      0     0  
67026                0.00171      0     0  
101166               0.00171      0     0  
4404                 0.00171      0     0  
...                      ...    ...   ...  
1239

In [4]:
explain_id = 0

In [5]:
# 找到id对应两跳的数据
expand_round = 2
ids = np.array([explain_id])
for _ in range(expand_round):
    cur_nodes = np.unique(np.concatenate([X[X['ID'].isin(ids)]['src_ip'].values, X[X['ID'].isin(ids)]['dst_ip'].values]))
    not_in_ids = X[~X['ID'].isin(ids)]
    not_in_ids = not_in_ids[(not_in_ids['src_ip'].isin(cur_nodes)) | (not_in_ids['dst_ip'].isin(cur_nodes))]
    if not_in_ids.shape[0] == 0:
        break
    ids = np.concatenate([ids, not_in_ids['ID'].values])

In [6]:
ids

array([     0,  12402,  35248,  45940,  80358,  88044, 124311, 137601],
      dtype=int64)

In [7]:
sub_X = X[X['ID'].isin(ids)].copy()

In [8]:
sub_X

ID               src_ip               dst_ip     proto   service  \
274326       0  172.27.226.140:1883  192.168.1.152:52976  0.798147  0.260632   
186690   12402    172.18.39.63:1883  192.168.1.152:52976  0.798147  0.260632   
314027   35248   172.19.66.179:1883  192.168.1.152:52976  0.798147  0.260632   
8118     45940  172.27.172.247:1883  192.168.1.152:52976  0.798147  0.260632   
147143   80358   172.27.229.31:1883  192.168.1.152:52976  0.798147  0.260632   
35392    88044   172.27.209.63:1883  192.168.1.152:52976  0.798147  0.260632   
109459  124311   172.26.209.32:1883  192.168.1.152:52976  0.798147  0.260632   
302083  137601   172.16.208.29:1883  192.168.1.152:52976  0.798147  0.260632   

          duration  src_bytes  dst_bytes  conn_state  missed_bytes  ...  \
274326  160.494251   0.125981   3.392807   -0.679894     -0.004621  ...   
186690   19.513205   0.007916   0.714913   -0.679894     -0.004621  ...   
314027   22.194187   0.010546   0.816154   -0.679894     -0.004621  ...   
8118     21.833927   0.010201   0.802269   -0.679894     -0.004621  ...   
147143    9.752800  -0.001549   0.352503   -0.679894     -0.004621  ...   
35392    21.695214   0.009828   0.787396   -0.679894     -0.004621  ...   
109459   22.357663   0.010712   0.821514   -0.679894     -0.004621  ...   
302083   22.843242   0.011182   0.840365   -0.679894     -0.004621  ...   

        http_trans_depth  http_method  http_version  http_request_body_len  \
274326          0.022966     0.021033      0.022685               -0.00539   
186690          0.022966     0.021033      0.022685               -0.00539   
314027          0.022966     0.021033      0.022685               -0.00539   
8118            0.022966     0.021033      0.022685               -0.00539   
147143          0.022966     0.021033      0.022685               -0.00539   
35392           0.022966     0.021033      0.022685               -0.00539   
109459          0.022966     0.021033      0.022685               -0.00539   
302083          0.022966     0.021033      0.022685               -0.00539   

        http_response_body_len  http_status_code  http_orig_mime_types  \
274326               -0.003103          0.018893              0.006307   
186690               -0.003103          0.018893              0.006307   
314027               -0.003103          0.018893              0.006307   
8118                 -0.003103          0.018893              0.006307   
147143               -0.003103          0.018893              0.006307   
35392                -0.003103          0.018893              0.006307   
109459               -0.003103          0.018893              0.006307   
302083               -0.003103          0.018893              0.006307   

        http_resp_mime_types  label  type  
274326               0.00171      0     0  
186690               0.00171      0     0  
314027               0.00171      0     0  
8118                 0.00171      0     0  
147143               0.00171      0     0  
35392                0.00171      0     0  
109459               0.00171      0     0  
302083               0.00171      0     0  

[8 rows x 35 columns]

In [9]:
norm_cols = X.columns.to_list()[3:-2]
X['h'] = X[norm_cols].values.tolist()
sub_X['h'] = sub_X[norm_cols].values.tolist()

In [10]:
norm_cols

['proto',
 'service',
 'duration',
 'src_bytes',
 'dst_bytes',
 'conn_state',
 'missed_bytes',
 'src_pkts',
 'src_ip_bytes',
 'dst_pkts',
 'dst_ip_bytes',
 'dns_qclass',
 'dns_qtype',
 'dns_rcode',
 'dns_AA',
 'dns_RD',
 'dns_RA',
 'dns_rejected',
 'ssl_version',
 'ssl_cipher',
 'ssl_resumed',
 'ssl_established',
 'http_trans_depth',
 'http_method',
 'http_version',
 'http_request_body_len',
 'http_response_body_len',
 'http_status_code',
 'http_orig_mime_types',
 'http_resp_mime_types']

In [11]:
from models.GraphSAGE import SAGE
from models.MLP import MLPPredictor
import torch.nn.functional as F
import torch.nn as nn
import networkx as nx
from dgl import from_networkx
import torch as th

eattrs = ['ID', 'h', 'label', 'type']
G = nx.from_pandas_edgelist(sub_X, 'src_ip', 'dst_ip', eattrs, create_using=nx.MultiGraph)
G = G.to_directed()
G = from_networkx(G, edge_attrs=eattrs)
G.ndata['h'] = th.ones(G.num_nodes(), G.edata['h'].shape[1])

feature_mask = nn.Parameter((th.ones(G.edata['h'].shape[1]) * 0.5).unsqueeze(0), requires_grad=True)
edge_mask = nn.Parameter((th.ones(G.edata['h'].shape[0]) * 0.5).unsqueeze(1), requires_grad=True)

class Model(nn.Module):
    def __init__(self, ndim_in, ndim_out, edim, activation, dropout, bin=False):
        super(Model, self).__init__()
        self.gnn = SAGE(ndim_in, ndim_out, edim, activation, dropout)
        if bin:
            self.pred = MLPPredictor(ndim_out, edim, 2)
        else:
            self.pred = MLPPredictor(ndim_out, edim, 10)
    def forward(self, g, nfeats, efeats):
        h = self.gnn(g, nfeats, efeats)
        return self.pred(g, h)
    
device = th.device('cuda' if th.cuda.is_available() else 'cpu')
print('Using device:', device)

params={
    'ndim_out': 128,
    'dropout': 0.2,
    'epochs': 500, # 2000
}
bin = False

# 加载模型
print('Loading model...')
model = Model(G.ndata['h'].shape[1], params['ndim_out'], G.edata['h'].shape[1], F.relu, params['dropout'], bin)
model.load_state_dict(th.load('pts/TON-IoT-p-ndim_out_128dropout_0.2epochs_500_multi(0.8653).pt'))

feature_mask = feature_mask.to(device)
edge_mask = edge_mask.to(device)
model = model.to(device)
G = G.to(device)
model.eval()

print(G.edata['h'])

pred_origin = model(G, G.ndata['h'], G.edata['h'])
pred_feature_masked = model(G, G.ndata['h'], G.edata['h'] * feature_mask)
pred_edge_masked = model(G, G.ndata['h'], G.edata['h'] * edge_mask)
print(pred_origin.argmax(dim=1))
print(G.edata['type'])

Using device: cuda
Loading model...
tensor([[ 7.9815e-01,  2.6063e-01,  1.6049e+02,  1.2598e-01,  3.3928e+00,
         -6.7989e-01, -4.6211e-03,  4.3083e+02,  7.9999e+01, -8.5059e-03,
         -9.9246e-03,  5.0886e-01,  4.8112e-01,  1.3839e-01,  5.0910e-01,
          4.7310e-01,  4.6947e-01,  4.6730e-01,  2.4579e-02,  2.4210e-02,
          3.8067e-02,  3.8061e-02,  2.2966e-02,  2.1033e-02,  2.2685e-02,
         -5.3905e-03, -3.1033e-03,  1.8893e-02,  6.3073e-03,  1.7101e-03],
        [ 7.9815e-01,  2.6063e-01,  1.6049e+02,  1.2598e-01,  3.3928e+00,
         -6.7989e-01, -4.6211e-03,  4.3083e+02,  7.9999e+01, -8.5059e-03,
         -9.9246e-03,  5.0886e-01,  4.8112e-01,  1.3839e-01,  5.0910e-01,
          4.7310e-01,  4.6947e-01,  4.6730e-01,  2.4579e-02,  2.4210e-02,
          3.8067e-02,  3.8061e-02,  2.2966e-02,  2.1033e-02,  2.2685e-02,
         -5.3905e-03, -3.1033e-03,  1.8893e-02,  6.3073e-03,  1.7101e-03],
        [ 7.9815e-01,  2.6063e-01,  1.9513e+01,  7.9162e-03,  7.1491e-01,


In [12]:
pred_origin.argmax(dim=1)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')

In [13]:
pred_origin[G.edata['ID'] == 0]

tensor([[ 1347.6316,   -87.6523,  1099.8977,   825.2758,  -747.4808,  -171.8368,
         -3119.6948,    27.1718, -2197.7913,   868.5677],
        [ 1434.4696,  -169.2266,  1190.9534,   956.7336,  -616.3792,  -179.2522,
         -3241.8501,   -25.9766, -2122.6528,   932.7032]], device='cuda:0',
       grad_fn=<IndexBackward0>)

In [14]:
def feature_mask_loss(g, pred_cur, feature_mask, edge_mask, eid):
    coeffs = {
        "pred": 3.0,
        "feat_size": 1.0,
        "feat_mask_ent": 0.1,
        "edge_size": 80.0,
        "edge_ent": 1.0
    }

    # MI loss
    label = g.edata['label'][eid]
    pred_loss = -th.log(pred_cur[eid][label])
    pred_loss = coeffs['pred'] * pred_loss

    # size
    feature_mask_sig = feature_mask.sigmoid()
    feature_mask_size_loss = coeffs['feat_size'] * th.mean(feature_mask_sig)
    edge_mask_sig = edge_mask.sigmoid()
    edge_mask_size_loss = coeffs['edge_size'] * th.mean(edge_mask_sig)

    # entropy
    feat_mask_ent = -feature_mask_sig * th.log(feature_mask_sig) - (1 - feature_mask_sig) * th.log(1 - feature_mask_sig)
    feat_mask_ent_loss = coeffs['feat_mask_ent'] * th.mean(feat_mask_ent)
    edge_mask_ent = -edge_mask_sig * th.log(edge_mask_sig) - (1 - edge_mask_sig) * th.log(1 - edge_mask_sig)
    edge_mask_ent_loss = coeffs['edge_ent'] * th.mean(edge_mask_ent)

    loss = pred_loss + feature_mask_size_loss + feat_mask_ent_loss + edge_mask_size_loss + edge_mask_ent_loss

    return loss

In [15]:
result_df = pd.DataFrame(columns=['ID', 'type'])

result_df['ID'] = th.tensor(G.edata['ID']).cpu().detach().numpy()
result_df['type'] = th.tensor(G.edata['type']).cpu().detach().numpy()
result_df['pred_origin'] = pred_origin.cpu().detach().numpy().tolist()
result_df['pred_feature_masked'] = pred_feature_masked.cpu().detach().numpy().tolist()
result_df['pred_edge_masked'] = pred_edge_masked.cpu().detach().numpy().tolist()

C:\Users\QishuoBai\AppData\Local\Temp\ipykernel_17224\629634806.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  result_df['ID'] = th.tensor(G.edata['ID']).cpu().detach().numpy()
C:\Users\QishuoBai\AppData\Local\Temp\ipykernel_17224\629634806.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  result_df['type'] = th.tensor(G.edata['type']).cpu().detach().numpy()


In [16]:
result_df

ID  type                                        pred_origin  \
0        0     0  [1347.631591796875, -87.65227508544922, 1099.8...   
1        0     0  [1434.4696044921875, -169.2266387939453, 1190....   
2    12402     0  [1199.6346435546875, -369.17901611328125, 857....   
3    35248     0  [1209.0985107421875, -363.43853759765625, 864....   
4    45940     0  [1199.5179443359375, -365.38201904296875, 857....   
5    80358     0  [1102.6715087890625, -422.6380310058594, 824.7...   
6    88044     0  [1246.2935791015625, -356.76641845703125, 877....   
7   124311     0  [1220.748291015625, -357.2375183105469, 860.24...   
8   137601     0  [1228.1290283203125, -355.6252136230469, 859.0...   
9    12402     0  [1215.8597412109375, -387.4450988769531, 866.0...   
10   35248     0  [1227.742431640625, -378.95220947265625, 871.7...   
11   45940     0  [1221.46484375, -384.8250732421875, 866.723449...   
12   80358     0  [1119.44091796875, -463.5238037109375, 840.960...   
13   88044     0  [1248.6241455078125, -355.6136169433594, 879.4...   
14  124311     0  [1238.847900390625, -369.8624267578125, 867.84...   
15  137601     0  [1245.5078125, -365.29168701171875, 866.252014...   

                                  pred_feature_masked  \
0   [660.0673217773438, -85.2056884765625, 565.997...   
1   [703.782470703125, -125.5407485961914, 610.360...   
2   [582.873291015625, -183.83712768554688, 434.22...   
3   [587.6033325195312, -180.9334259033203, 437.17...   
4   [582.949462890625, -180.87779235839844, 433.88...   
5   [535.9268798828125, -208.19761657714844, 419.2...   
6   [605.2543334960938, -181.492431640625, 444.278...   
7   [592.9841918945312, -177.62326049804688, 435.4...   
8   [596.447998046875, -177.18017578125, 434.76370...   
9   [591.1207885742188, -193.11798095703125, 438.3...   
10  [597.0602416992188, -188.83811950683594, 440.9...   
11  [594.0487670898438, -190.74729919433594, 438.5...   
12  [544.4737548828125, -228.7770538330078, 427.48...   
13  [606.387939453125, -180.88809204101562, 445.20...   
14  [602.0894165039062, -184.11692810058594, 439.2...   
15  [605.0723266601562, -182.03013610839844, 438.3...   

                                     pred_edge_masked  
0   [660.0673217773438, -85.2056884765625, 565.997...  
1   [703.782470703125, -125.5407485961914, 610.360...  
2   [582.873291015625, -183.83712768554688, 434.22...  
3   [587.6033325195312, -180.9334259033203, 437.17...  
4   [582.949462890625, -180.87779235839844, 433.88...  
5   [535.9268798828125, -208.19761657714844, 419.2...  
6   [605.2543334960938, -181.492431640625, 444.278...  
7   [592.9841918945312, -177.62326049804688, 435.4...  
8   [596.447998046875, -177.18017578125, 434.76370...  
9   [591.1207885742188, -193.11798095703125, 438.3...  
10  [597.0602416992188, -188.83811950683594, 440.9...  
11  [594.0487670898438, -190.74729919433594, 438.5...  
12  [544.4737548828125, -228.7770538330078, 427.48...  
13  [606.387939453125, -180.88809204101562, 445.20...  
14  [602.0894165039062, -184.11692810058594, 439.2...  
15  [605.0723266601562, -182.03013610839844, 438.3...